# Unless explicitly stated otherwise all files in this repository are dual-licensed
# under the Apache 2.0 or BSD3 Licenses.
#
# This product includes software developed at Datadog (https://www.datadoghq.com/)
# Copyright 2022 Datadog, Inc.
FROM python:3.9

WORKDIR /home

COPY requirements.txt /home
COPY notes_app /home/notes_app

ENV DD_SERVICE="notes"
ENV DD_ENV="dd_apm_learning"
ENV DD_VERSION="0.3.0"

LABEL com.datadoghq.tags.service="notes"
LABEL com.datadoghq.tags.env="dd_apm_learning"
LABEL com.datadoghq.tags.version="0.3.0"

RUN pip install -r requirements.txt

# Run the application without the Datadog agent or tracing
CMD ["ddtrace-run", "python", "-m", "notes_app.app"]
